# Please read comments in environment.yml
channels:
  - conda-forge
  - defaults
dependencies:
  - bump2version
  - cookiecutter
  - flake8
  - pytest
  - pytest-cov
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-apidoc
  - sphinxcontrib-autoprogram
  - tox
  - twine
